version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  allow:
    - dependency-type: "direct"

- package-ecosystem: "npm"
  directory: "/packages/modal-component"
  schedule:
    interval: "weekly"
  allow:
    - dependency-type: "direct"

- package-ecosystem: "npm"
  directory: "/packages/modal-dashboard"
  schedule:
    interval: "weekly"
  allow:
    - dependency-type: "direct"
